---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: ingress presence
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    asserts:
      - hasDocuments:
          count: 1
      - documentIndex: 0
        not: true
        isKind:
          of: Ingress

  - it: explicitly disabled should pass
    values:
      - ../_values/ingress_main_default_hosts.yaml
    set:
      ingress.main.enabled: false
    asserts:
      - hasDocuments:
          count: 1
      - documentIndex: 0
        not: true
        isKind:
          of: Ingress

  - it: explicitly enabled should pass
    values:
      - ../_values/ingress_main_default_hosts.yaml
    set:
      ingress.main.enabled: true
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: 0
        not: true
        isKind:
          of: Ingress
      - documentIndex: 1
        isKind:
          of: Ingress

  - it: multiple ingress should pass
    values:
      - ../_values/service_main_default.yaml
      - ../_values/ingress_main_default_hosts.yaml
    set:
      ingress.test:
        hosts:
          - host: "chart-example.local"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    asserts:
      - hasDocuments:
          count: 4
      - documentIndex: 0
        not: true
        isKind:
          of: Ingress
      - documentIndex: 1
        not: true
        isKind:
          of: Ingress
      - documentIndex: &FirstIngressDocument 2
        isKind:
          of: Ingress
      - documentIndex: *FirstIngressDocument
        equal:
          path: metadata.name
          value: RELEASE-NAME-main
      - documentIndex: &SecondIngressDocument 3
        isKind:
          of: Ingress
      - documentIndex: *SecondIngressDocument
        equal:
          path: metadata.name
          value: RELEASE-NAME-test

  - it: multiple ingress with explicit disabled should pass
    values:
      - ../_values/ingress_main_default_hosts.yaml
    set:
      ingress.test:
        enabled: false
        hosts:
          - host: "chart-example.local"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: 0
        not: true
        isKind:
          of: Ingress
      - documentIndex: &FirstIngressDocument 1
        isKind:
          of: Ingress
      - documentIndex: *FirstIngressDocument
        equal:
          path: metadata.name
          value: RELEASE-NAME
