---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: serviceAccount - presence
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: serviceAccount is not created by default
    asserts:
      - not: true
        containsDocument:
          apiVersion: v1
          kind: ServiceAccount
          any: true

  - it: serviceAccounts are enabled by default
    set:
      serviceAccount:
        main: {}
    asserts:
      - containsDocument:
          kind: ServiceAccount
          apiVersion: v1
          name: release-name
          any: true
      - documentSelector:
          path: $[?(@.kind == "ServiceAccount")].metadata.name
          value: release-name
        equal:
          path: secrets
          value:
            - name: release-name-main-sa-token
      - containsDocument:
          kind: Secret
          apiVersion: v1
          name: release-name-main-sa-token
          any: true
      - documentSelector:
          path: $[?(@.kind == "Secret")].metadata.name
          value: release-name-main-sa-token
        equal:
          path: metadata.annotations
          value:
            kubernetes.io/service-account.name: release-name

  - it: serviceAccounts can be disabled
    set:
      serviceAccount:
        default:
          enabled: false
    asserts:
      - not: true
        containsDocument:
          apiVersion: v1
          kind: ServiceAccount
          name: release-name
          any: true

  - it: multiple serviceAccounts can be enabled
    set:
      serviceAccount:
        myAccount: {}
        mySA: {}
        mySA2:
          enabled: false
    asserts:
      - documentSelector:
          path: $[?(@.kind == "ServiceAccount")].metadata.name
          value: release-name-myaccount
        equal:
          path: secrets
          value:
            - name: release-name-myaccount-sa-token
      - documentSelector:
          path: $[?(@.kind == "Secret")].metadata.name
          value: release-name-myaccount-sa-token
        equal:
          path: metadata.annotations
          value:
            kubernetes.io/service-account.name: release-name-myaccount
      - documentSelector:
          path: $[?(@.kind == "ServiceAccount")].metadata.name
          value: release-name-mysa
        equal:
          path: secrets
          value:
            - name: release-name-mysa-sa-token
      - documentSelector:
          path: $[?(@.kind == "Secret")].metadata.name
          value: release-name-mysa-sa-token
        equal:
          path: metadata.annotations
          value:
            kubernetes.io/service-account.name: release-name-mysa
      - not: true
        containsDocument:
          apiVersion: v1
          kind: ServiceAccount
          name: release-name-mysa2
          any: true
      - not: true
        containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-mysa2-sa-token
          any: true
