---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pod - fields - nodeSelector
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - notExists:
          path: spec.template.spec.nodeSelector

  - it: defaultPodOption should pass
    set:
      defaultPodOptions:
        nodeSelector:
          disktype: ssd
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.nodeSelector
          value:
            disktype: ssd

  - it: defaultPodOption with pod override should pass
    set:
      defaultPodOptions:
        nodeSelector:
          disktype: ssd
      controllers:
        main:
          pod:
            nodeSelector:
              disktype: hdd
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - documentIndex: 0
        equal:
          path: spec.template.spec.nodeSelector
          value:
            disktype: hdd
