---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pod - fields - automountServiceAccountToken
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: should be set to false by default
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.automountServiceAccountToken
          value: false

  - it: can be overriden on the Pod level
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    set:
      controllers:
        main:
          pod:
            automountServiceAccountToken: true
    asserts:
      - equal:
          path: spec.template.spec.automountServiceAccountToken
          value: true

  - it: can be overriden on the defaultPodOption level
    set:
      defaultPodOptions:
        automountServiceAccountToken: true
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.automountServiceAccountToken
          value: true
