---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pod replicas
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    asserts:
      - documentIndex: 0
        isKind:
          of: Deployment
      - documentIndex: 0
        equal:
          path: spec.replicas
          value: 1

  - it: nil should pass
    set:
      controllers.main.replicas: null
    asserts:
      - documentIndex: 0
        isKind:
          of: Deployment
      - documentIndex: 0
        notExists:
          path: spec.replicas

  - it: custom replicas should pass
    set:
      controllers.main.replicas: 3
    asserts:
      - documentIndex: 0
        isKind:
          of: Deployment
      - documentIndex: 0
        equal:
          path: spec.replicas
          value: 3
