---
apiVersion: v2
description: A common powered chart template. This can be useful for small projects that don't have their own chart.
name: app-template
version: 3.7.2
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.7.2
annotations:
  org.opencontainers.image.source: "https://github.com/bjw-s/helm-charts"
  artifacthub.io/changes: |-
    - kind: added
      description: |-
        The Apache 2.0 LICENSE file has been added to the chart.
