---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: route metadata
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default metadata should pass
    set:
      route.main:
        parentRefs:
          - name: test
            namespace: test
    asserts:
      - documentIndex: &routeDocument 1
        isKind:
          of: HTTPRoute
      - documentIndex: *routeDocument
        notExists:
          path: metadata.annotations
      - documentIndex: *routeDocument
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0

  - it: custom metadata should pass
    set:
      route.main:
        annotations:
          test_annotation: test
        labels:
          test_label: test
        parentRefs:
          - name: test
            namespace: test
    asserts:
      - documentIndex: &routeDocument 1
        isKind:
          of: HTTPRoute
      - documentIndex: *routeDocument
        equal:
          path: metadata.annotations
          value:
            test_annotation: test
      - documentIndex: *routeDocument
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0
            test_label: test

  - it: custom metadata with global metadata should pass
    set:
      global:
        labels:
          global_label: test
        annotations:
          global_annotation: test
      route.main:
        annotations:
          test_annotation: test
        labels:
          test_label: test
        parentRefs:
          - name: test
            namespace: test
    asserts:
      - documentIndex: &routeDocument 1
        isKind:
          of: HTTPRoute
      - documentIndex: *routeDocument
        equal:
          path: metadata.annotations
          value:
            global_annotation: test
            test_annotation: test
      - documentIndex: *routeDocument
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            global_label: test
            helm.sh/chart: common-test-1.0.0
            test_label: test
