---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: route names
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default name
    set:
      route.main:
        enabled: true
        parentRefs:
          - name: test
            namespace: test
    documentSelector:
      path: $[?(@.kind == "HTTPRoute")].metadata.name
      value: RELEASE-NAME
    asserts:
      - exists:
          path: metadata.name

  - it: custom name suffix
    set:
      route.main:
        enabled: true
        parentRefs:
          - name: test
            namespace: test
        nameOverride: http
    documentSelector:
      path: $[?(@.kind == "HTTPRoute")].metadata.name
      value: RELEASE-NAME-http
    asserts:
      - exists:
          path: metadata.name

  - it: custom name suffix with template
    set:
      route.main:
        enabled: true
        parentRefs:
          - name: test
            namespace: test
        nameOverride: "{{ .Chart.Name }}"
    documentSelector:
      path: $[?(@.kind == "HTTPRoute")].metadata.name
      value: RELEASE-NAME-common-test
    asserts:
      - exists:
          path: metadata.name

  - it: multiple routes
    set:
      route:
        main:
          parentRefs:
            - name: main
              namespace: main
        test:
          parentRefs:
            - name: test
              namespace: test
    asserts:
      - documentSelector:
          path: $[?(@.kind == "HTTPRoute")].metadata.name
          value: RELEASE-NAME-main
        exists:
          path: metadata.name
      - documentSelector:
          path: $[?(@.kind == "HTTPRoute")].metadata.name
          value: RELEASE-NAME-test
        exists:
          path: metadata.name
