---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: route presence
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    asserts:
      - hasDocuments:
          count: 1
      - documentIndex: 0
        not: true
        isKind:
          of: HTTPRoute

  - it: explicitly disabled should pass
    set:
      route.main.enabled: false
    asserts:
      - hasDocuments:
          count: 1
      - documentIndex: 0
        not: true
        isKind:
          of: HTTPRoute

  - it: explicitly enabled should pass
    set:
      route.main:
        enabled: true
        parentRefs:
          - name: test
            namespace: test
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: 0
        not: true
        isKind:
          of: HTTPRoute
      - documentIndex: 1
        isKind:
          of: HTTPRoute

  - it: multiple enabled should pass
    set:
      route:
        main:
          parentRefs:
            - name: main
              namespace: main
        test:
          parentRefs:
            - name: test
              namespace: test
    asserts:
      - hasDocuments:
          count: 3
      - documentIndex: 0
        not: true
        isKind:
          of: HTTPRoute
      - documentIndex: 1
        isKind:
          of: HTTPRoute
      - documentIndex: 2
        isKind:
          of: HTTPRoute
