---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: rawResource metadata
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  rawResources:
    config:
      apiVersion: v1
      kind: Endpoint
      spec:
        test: test
tests:
  - it: default metadata should be present
    documentSelector: &EndpointSelector
      path: $[?(@.kind == "Endpoint")].metadata.name
      value: RELEASE-NAME-config
    asserts:
      - notExists:
          path: metadata.annotations
      - equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0

  - it: custom metadata can be configured
    set:
      rawResources:
        config:
          annotations:
            test_annotation: test
          labels:
            test_label: test
    documentSelector: *EndpointSelector
    asserts:
      - equal:
          path: metadata.annotations
          value:
            test_annotation: test
      - equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0
            test_label: test

  - it: global metadata can be configured with local overrides
    set:
      global:
        labels:
          global_label: test
        annotations:
          global_annotation: test
      rawResources:
        config:
          annotations:
            test_annotation: test
          labels:
            test_label: test
    documentSelector: *EndpointSelector
    asserts:
      - equal:
          path: metadata.annotations
          value:
            global_annotation: test
            test_annotation: test
      - equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            global_label: test
            helm.sh/chart: common-test-1.0.0
            test_label: test
