---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: misc - global nameOverride test
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default name is set to release name
    asserts:
      - containsDocument:
          apiVersion: apps/v1
          kind: Deployment
          name: release-name
          any: true

  - it: global.nameOverride can be set
    set:
      global.nameOverride: custom-name
    asserts:
      - containsDocument:
          apiVersion: apps/v1
          kind: Deployment
          name: release-name-custom-name
          any: true
