---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 3.7.0
kubeVersion: ">=1.22.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: |-
        Only add hostUsers when explicitly configured
    - kind: fixed
      description: |-
        `hosts` should be an optional field for Ingress resources
    - kind: fixed
      description: |-
        `defaultBackend` should be an object for Ingress resources
