---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 5.2.0
kubeVersion: ">=1.31.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s-labs/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
sources:
  - https://github.com/bjw-s-labs/helm-charts
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: |-
        Added support for ExternalSecret resources
    - kind: added
      description: |-
        Added support for CiliumNetworkPolicy resources
    - kind: fixed
      description: |-
        Fixed NetworkPolicy extraSelectorLabels precedence over generated selector labels
    - kind: added
      description: |-
        Added initial support for ListenerSet resources
    - kind: added
      description: |-
        Added default selectors to topologySpreadConstraints to the same controller
    - kind: added
      description: |-
        Added native support for `projected` persistence items
