---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: service - validations
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: invalid controller reference should fail
    set:
      service:
        main:
          controller: other
    asserts:
      - failedTemplate:
          errorMessage: "No enabled controller found with this identifier. (service: 'main', controller: 'other')"

  - it: no ports enabled should fail
    values:
      - ../_values/service_main_default.yaml
    set:
      service:
        main:
          ports:
            http:
              enabled: false
    asserts:
      - failedTemplate:
          errorMessage: "No ports are enabled for Service with this identifier. (service: 'main')"
