name: "Charts: Release to GitHub pages"

on:
  workflow_call:
    inputs:
      artifactPattern:
        type: string
        description: "Pattern to match artifacts to release"
        required: true

jobs:
  release-charts:
    name: Release charts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages
          fetch-depth: 0

      - name: Prepare artifacts folder
        shell: bash
        run: |
          mkdir -p artifacts

      - name: Download chart artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: ${{ inputs.artifactPattern }}

      - name: Copy artifacts to gh-pages structure
        shell: bash
        run: |
          CHARTS=$( ls artifacts/ )
          for CHART in "${CHARTS[@]}" ; do
            DELIMITER='__'
            s=${CHART}${DELIMITER}
            CHART_PATH_PARTS=();
            while [[ $s ]]; do
                CHART_PATH_PARTS+=( "${s%%"${DELIMITER}"*}" );
                s=${s#*"${DELIMITER}"};
            done;

            CHART_FOLDER=${CHART_PATH_PARTS[0]}
            mkdir -p "gh-pages/${CHART_FOLDER}"
            cp artifacts/${CHART}/* gh-pages/${CHART_FOLDER}/
          done

      - name: Update chart index
        shell: bash
        working-directory: gh-pages
        run: |
          helm repo index . --url https://bjw-s.github.io/helm-charts/

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: gh-pages
          branch: gh-pages
          commit_user_name: "bjw-s-bot[bot]"
          commit_user_email: 87358111+bjw-s-bot[bot]@users.noreply.github.com
          commit_author: bjw-s-bot[bot] <87358111+bjw-s-bot[bot]@users.noreply.github.com>
          file_pattern: "index.yaml **/*.tgz"
          disable_globbing: true

      - name: Publish changes to GitHub Pages
        uses: ./src/.github/actions/publish-folder-to-pages
        with:
          path: gh-pages/
          deleteArtifactAfterPublish: true
