---
name: "Charts: Release"

concurrency: helm-release

on:
  workflow_dispatch:
    inputs:
      charts:
        description: "JSON encoded list of charts to release"
        required: true
        type: string
        default: "[]"
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  prepare:
    name: Prepare data required for workflow
    runs-on: ubuntu-22.04
    outputs:
      repoConfiguration: ${{ steps.repo-config.outputs.config }}
      libraryChartsToRelease: ${{ steps.changed-library-charts.outputs.all_changed_files }}
      otherChartsToRelease: ${{ steps.changed-charts.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Grab repository configuration
        id: repo-config
        shell: bash
        run: |
          echo "config=$(yq '.' '.ci/repo-config.yaml' -o json -I=0)" >> "$GITHUB_OUTPUT"

      - name: Get changed library charts
        id: changed-library-charts
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          path: charts
          dir_names: true
          dir_names_max_depth: 2
          files: |
            library/**

      - name: Get changed charts
        id: changed-charts
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          path: charts
          dir_names: true
          dir_names_max_depth: 2
          files_ignore: |
            library/**

      - name: Get specified charts
        id: specified-charts
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/github-script@v7
        with:
          script: |
            const input = '${{ github.event.inputs.charts }}';
            const charts = JSON.parse(input);
            const libraryCharts = charts.filter(chart => chart.startsWith('library/'));
            console.log(JSON.stringify(libraryCharts));
            // core.setOutput('libraryChartsToRelease', JSON.stringify(libraryCharts));

  release-library-charts:
    name: Release library charts
    needs:
      - prepare
    if: ${{ needs.prepare.outputs.libraryChartsToRelease != '[]' && needs.prepare.outputs.libraryChartsToRelease != '' }}
    uses: ./.github/workflows/charts-release-steps.yaml
    permissions:
      pages: write
      id-token: write
      contents: write
      packages: write
    with:
      charts: ${{ needs.prepare.outputs.libraryChartsToRelease }}
      excludedChartsRelease: ${{ toJSON(fromJSON(needs.prepare.outputs.repoConfiguration).excluded-charts-release) }}
      ghPagesBranch: gh-pages
      publishToOciRegistry: false

  release-other-charts:
    name: Release other charts
    needs:
      - prepare
      - release-library-charts
    if: |
      ${{
        always() &&
        !failure() && !cancelled() &&
        needs.prepare.outputs.otherChartsToRelease != '[]' && needs.prepare.outputs.otherChartsToRelease != ''
      }}
    uses: ./.github/workflows/charts-release-steps.yaml
    permissions:
      pages: write
      id-token: write
      contents: write
      packages: write
    with:
      charts: ${{ needs.prepare.outputs.otherChartsToRelease }}
      excludedChartsRelease: ${{ toJSON(fromJSON(needs.prepare.outputs.repoConfiguration).excluded-charts-release) }}
      ghPagesBranch: gh-pages
