---
name: "Charts: Release"

concurrency: helm-release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rework-publishing-ci
    paths:
      - "charts/**"

jobs:
  prepare-release:
    name: Prepare data required for release
    runs-on: ubuntu-22.04
    outputs:
      repoConfiguration: ${{ steps.repo-config.outputs.config }}
      libraryChartsToRelease: ${{ steps.changed-library-charts.outputs.all_changed_files }}
      applicationChartsToRelease: ${{ steps.changed-charts.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Grab repository configuration
        id: repo-config
        shell: bash
        run: |
          echo "config=$(yq '.' '.ci/repo-config.yaml' -o json -I=0)" >> "$GITHUB_OUTPUT"

      - name: Get changed library charts
        id: changed-library-charts
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          base_sha: main  # TODO: Remove this
          path: charts
          dir_names: true
          dir_names_max_depth: 2
          files: |
            library/**

      - name: Get changed charts
        id: changed-charts
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          base_sha: main  # TODO: Remove this
          path: charts
          dir_names: true
          dir_names_max_depth: 2
          files_ignore: |
            library/**

  release-library-charts:
    name: Release library charts
    needs:
      - prepare-release
    if: ${{ needs.prepare-release.outputs.libraryChartsToRelease != '[]' }}
    uses: ./.github/workflows/charts-release-steps.yaml
    permissions:
      pages: write
      id-token: write
      contents: write
    with:
      charts: ${{ needs.prepare-release.outputs.libraryChartsToRelease }}
      excludedChartsRelease: ${{ toJSON(fromJSON(needs.prepare-release.outputs.repoConfiguration).excluded-charts-release) }}
      ghPagesBranch: gh-pages

  #   name: Release charts
  #   runs-on: ubuntu-22.04
  #   needs:
  #     - changed-charts
  #     - release-library-charts
  #   strategy:
  #     matrix:
  #       charts: ${{ fromJSON(needs.prepare-release.outputs.applicationChartsToRelease) }}
  #     max-parallel: 2
  #     fail-fast: false
  #   steps:
  #     - name: Echo chart folder
  #       if: ${{ !contains(fromJSON(needs.prepare-release.outputs.repoConfiguration).excluded-charts-release, matrix.charts) }}
  #       run: |
  #         echo ${{ matrix.charts }}

  #   uses: ./.github/workflows/charts-release-ghpages.yaml
  #   with:
  #     charts: "${{ needs.prepare.outputs.libraryChartsToRelease }}"
  #   secrets: inherit

  # tag-library-charts:
  #   name: Create git tags for library charts
  #   uses: ./.github/workflows/tag-charts.yaml
  #   needs:
  #     - prepare
  #     - release-library-charts
  #   with:
  #     charts: "${{ needs.prepare.outputs.libraryChartsToRelease }}"
  #   secrets: inherit

  # release-application-charts:
  #   name: Release Application charts to GitHub pages
  #   uses: ./.github/workflows/charts-release-ghpages.yaml
  #   needs:
  #     - prepare
  #     - release-library-charts
  #   with:
  #     charts: "${{ needs.prepare.outputs.applicationChartsToRelease }}"
  #   secrets: inherit

  # tag-application-charts:
  #   name: Create git tags for application charts
  #   uses: ./.github/workflows/tag-charts.yaml
  #   needs:
  #     - prepare
  #     - release-application-charts
  #   with:
  #     charts: "${{ needs.prepare.outputs.applicationChartsToRelease }}"
  #   secrets: inherit

  # release-github-oci:
  #   name: Release Application charts to GitHub Container Registry
  #   uses: ./.github/workflows/charts-release-oci.yaml
  #   needs:
  #     - prepare
  #     - release-library-charts
  #   with:
  #     charts: "${{ needs.prepare.outputs.applicationChartsToRelease }}"
  #   secrets: inherit
