---
name: "Docs: Release to GitHub pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs-release.yaml"
      - "docs/**"
      - "charts/library/common/schemas/**"
      - "charts/library/common/values.schema.json"
      - "tools/helm-schema-tools/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Mise and required tools
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          cache_key: "mise-v1-{{file_hash}}"

      - name: Build Go tool
        run: |
          cd tools/helm-schema-tools
          go build -o helm-schema-tools ./cmd/helm-schema-tools/

      - name: Generate reference docs and schema
        run: just docs::generate

      - name: Build Starlight site
        run: just docs::build

      - name: Generate Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          publish_dir: ./docs/dist
          destination_dir: docs

  publish-docs:
    name: Publish documentation
    runs-on: ubuntu-24.04
    needs:
      - build-docs
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: src
          persist-credentials: false

      - name: Checkout gh-pages branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: false

      - name: Deploy to GitHub Pages
        uses: ./src/.github/actions/publish-folder-to-pages
        with:
          path: gh-pages/
          deleteArtifactAfterPublish: true
