rbac:
  bindings:
    defaultBinding:
      enabled: true
      type: RoleBinding
      roleRef:
        name: defaultBinding
        kind: Role
      subjects:
      - kind: Group
        name: oidc:/default-group
      - kind: User
        name: default-username
      - kind: ServiceAccount
        name: default
        namespace: default
